### ISSUE TITLE
Last 10 trades are actually the first 10 trades

### ISSUE THREAD

**Issue by cyberjunky** [stash86/ft-dashboard#5]
It starts at 1, instead from now to the back
![image](https://github.com/stash86/ft-dashboard/assets/5447161/167de8d9-f337-4c9d-b82b-cb8c23561809)

**Comment by cyberjunky** [comment]
order_by_id=False for trades api calls doesn't seems to do it's job.

**Comment by stash86** [comment]
Did you do any changes around that part before?

**Comment by cyberjunky** [comment]
Same 'fix' as the other issue with the graphs; really no idea why the api call param doesn't work here yet, are you on stable branch or developer?
in rpc/api_server/api_v1.py around line 120:
```
# Using the responsemodel here will cause a ~100% increase in response time (from 1s to 2s)
# on big databases. Correct response model: response_model=TradeResponse,
@router.get('/trades', tags=['info', 'trading'])
def trades(limit: int = 500, offset: int = 0, rpc: RPC = Depends(get_rpc)):
    return rpc._rpc_trade_history(limit, offset=offset, order_by_id=False)
```

**Comment by cyberjunky** [comment]
My freqtrade was pure stable code, no local code changes of any kind. apart from this order_by_id=False now

**Comment by cyberjunky** [comment]
Looked if I could find a related fix or issue, but haven't found any, and frequi works fine without the hack

**Comment by stash86** [comment]
I just recently add code to forcefully sort chart data by close date. The last 10 trades column would still be wrong, but at least you can get the chart right for now. Still working to get the closed trades table to be fixed as well

**Comment by cyberjunky** [comment]
> I just recently add code to forcefully sort chart data by close date. The last 10 trades column would still be wrong, but at least you can get the chart right for now. Still working to get the closed trades table to be fixed as well

Thanks a lot, I will try it out shorty, upgrading to freqtrade 2023.09 as we speak first, better Bybit support yeah!
