### ISSUE TITLE
Strategy name is not unique

### ISSUE THREAD

**Issue by amargedon** [stash86/ft-dashboard#6]
First of all; thanks for this dashboard and sharing it! I'm currently working on a trading strategy and I'm running this strategy in dry-run on multiple timeframes (1h, 2h, 4h, 1d, 1w) to compare (that's also why I would love to use this dashboard!). So, the strategy name is the same on all five bots and in the config.json the timeframe is specified. 

The dashboard cron job is collecting data, however, in the dashboard only the results for one bot are shown. I think the main reason is because fetch_data.php is using the strategy_name as key. In my case the same strategy is running five times, so yeah...

Does this seem the correct analysis? Would it be possible to use the bot_name as unique key, or make the key a combination of bot_name and strategy_name? Or do you have another solution or opinion on this?

**Comment by stash86** [comment]
pull latest version. You need to add `BOT_NAME_AS_INDEX=true` on your `.env` file, then wait until the next time the script fetch data from bots

example of how it looks like http://ft-dashboard.ddns.net/

**Comment by amargedon** [comment]
Can confirm this is working, thanks!
